### ISSUE TITLE
Fileextensions with dots (bgeo.sc) not handled as sequences

### ISSUE THREAD

**Issue by Eiken** [justinfx/gofileseq#11]
Running seqls in a folder containing bgeo.sc file sequences returns individual files as result.

**Comment by justinfx** [comment]
Thanks for the report on this. I took a look at this last night. What platform are you running, so that I can give you a test binary. Otherwise I can just tag 2.6.0 today.

**Comment by Eiken** [comment]
We are running Centos7

**Comment by Eiken** [comment]
Linux 64bit in other words

**Comment by justinfx** [comment]
Sweet. I have tagged a new[ 2.5.1 release](https://github.com/justinfx/gofileseq/releases/tag/v2.5.1) with this fix

**Comment by Eiken** [comment]
Thanks!

Works like a charm. Will make one of our houdini peeps very happy.
