### ISSUE TITLE
include support for creating file sequences from a slice ala findSequencesInList

### ISSUE THREAD

**Issue by brianwells123** [justinfx/gofileseq#17]
It would be great for gofileseq to include support similar to [findSequencesInList](https://github.com/justinfx/fileseq/blob/master/src/fileseq/filesequence.py#L866) from the python fileseq. This would make it far simpler to:
- iterate through file sequences
- split them into chunks based on specific criteria (size, count, etc)
- place them back into a "minified" fileseq representation for efficient storage
Thaanks!

**Comment by justinfx** [comment]
@brianwells123 can you have a look at #18 and see if it does what you need?
