### ISSUE TITLE
issue with parsing single files or sequences with numeric suffixes

### ISSUE THREAD

**Issue by brianwells123** [justinfx/gofileseq#19]
this example will illustrate the problem:
https://play.golang.org/p/8g8jxJidKK0

however it will work fine if the last character is alpha:
https://play.golang.org/p/Jwsxi6dBQBx

**Comment by justinfx** [comment]
@brianwells123 I found a couple bugs related to this issue. 

The first problem you were hitting was that the regex matching `/path/file.ext12345` was matching it as a sequence  `/path/file.ext12345@@@@@`  but then the `NewFileSequence` constructor was not happy about a required "." character needing to be in the extension. I've updated the regex for that case.

Then there was the issue that it was even being detected as a sequence, when you probably want it detected as a single non-sequence file:

```
// actual
base: file.ext , frame:  12345 , ext:

// expected
base: file , frame:   , ext:  .ext12345
```

So I have further updated the regexes to use an optional frame component when doing `findSequenceInList` and to test the matched base/frame/ext parts, and then assemble a correct single-file result.

You can look at the tests to see the current cases. Let me know if there is another case that is missing?

**Comment by brianwells123** [comment]
Sure, let me check. I I know for sure I had a case where the file had no extension, like `/tmp/tempfiles/env2`.

**Comment by justinfx** [comment]
@brianwells123  I forgot to submit the PR. Here is the test where we are looking at files with no extension:
https://github.com/justinfx/gofileseq/pull/20/files#diff-3d61ed43bbc3116833139d80facfaca8abf390c680af3bfcf624199e1ea9821cR822
